server:
  port: 8093
spring:
  config:
    import: optional:file:./.env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  application:
    name: comments
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_KEY}
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

eureka:
  instance:
    hostname: localhost
